services:
  mc-panel:
    image: minecraft-ag-panel:latest
    container_name: minecraft_ag_panel
    restart: unless-stopped
    env_file: 
      - /home/$USER/minecraft.ag/.env
    volumes:
      - /home/$USER/minecraft:/minecraft
      - /home/$USER/world_backups:/world_backups
    ports:
      - "127.0.0.1:$PORT:$PORT/tcp"
      - "127.0.0.1:59134:19134/udp"
      - "127.0.0.1:59135:19135/udp"
      # - "$MCPORT:$MCPORT/udp"
      # - "$MCPORTV6:$MCPORTV6/udp"
