[project]
name = "panel"
version = "0.1.0"
description = "Django Bedrock Panel"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.2",
    "django-ratelimit>=4.1.0",
    "gunicorn>=25.0.3",
    "mcstatus>=12.2.1",
    "psutil>=7.2.2",
    "python-decouple>=3.8",
]

[dependency-groups]
dev = [
    "whitenoise>=6.11.0",
]
